/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedJamJamIdRouteImport } from './routes/(protected)/jam/$jamId'
import { Route as protectedJamJoinJamIdRouteImport } from './routes/(protected)/jam/join/$jamId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/(protected)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedJamJamIdRoute = protectedJamJamIdRouteImport.update({
  id: '/(protected)/jam/$jamId',
  path: '/jam/$jamId',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedJamJoinJamIdRoute = protectedJamJoinJamIdRouteImport.update({
  id: '/(protected)/jam/join/$jamId',
  path: '/jam/join/$jamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof protectedDashboardRoute
  '/jam/$jamId': typeof protectedJamJamIdRoute
  '/jam/join/$jamId': typeof protectedJamJoinJamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof protectedDashboardRoute
  '/jam/$jamId': typeof protectedJamJamIdRoute
  '/jam/join/$jamId': typeof protectedJamJoinJamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(protected)/jam/$jamId': typeof protectedJamJamIdRoute
  '/(protected)/jam/join/$jamId': typeof protectedJamJoinJamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/jam/$jamId' | '/jam/join/$jamId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/jam/$jamId' | '/jam/join/$jamId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(protected)/dashboard'
    | '/(protected)/jam/$jamId'
    | '/(protected)/jam/join/$jamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedJamJamIdRoute: typeof protectedJamJamIdRoute
  protectedJamJoinJamIdRoute: typeof protectedJamJoinJamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/jam/$jamId': {
      id: '/(protected)/jam/$jamId'
      path: '/jam/$jamId'
      fullPath: '/jam/$jamId'
      preLoaderRoute: typeof protectedJamJamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/jam/join/$jamId': {
      id: '/(protected)/jam/join/$jamId'
      path: '/jam/join/$jamId'
      fullPath: '/jam/join/$jamId'
      preLoaderRoute: typeof protectedJamJoinJamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  protectedDashboardRoute: protectedDashboardRoute,
  protectedJamJamIdRoute: protectedJamJamIdRoute,
  protectedJamJoinJamIdRoute: protectedJamJoinJamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
